version: "3"

tasks:
  # -------------------------------------------------
  # ----------------- GENERAL TASKS -----------------
  # -------------------------------------------------

  dev:
    cmds:
      - defer: npx kill-port 8080
      - |
        concurrently \
        -n "functions, firebase,   client" \
        "task build_functions_watch" \
        "task emulate_firebase" \
        "task emulate_client" \
        --kill-others-on-fail \
        --prefix-length 9 \
        --max-processes 3 \
        --success first \
        --prefix-colors red.bold,yellow.bold,blue.bold \
        --prefix "[{time} - {name}]" \
        --timestamp-format HH:mm:ss

  install:
    deps:
      - install_client
      - install_functions

  deploy:
    deps:
      - deploy_functions
      - deploy_client

  # ------------------------------------------------
  # ----------------- CLIENT TASKS -----------------
  # ------------------------------------------------

  install_client:
    cmds:
      - cd client && npm install

  emulate_client:
    cmds:
      - npm run start --prefix client

  build_client:
    cmds:
      - npm run build --prefix client
    sources:
      - client/src/**/*
    generates:
      - client/build/**/*
    method: timestamp

  deploy_client:
    deps:
      - build_client
    cmds:
      - firebase deploy --only hosting

  # --------------------------------------------------
  # ----------------- FIREBASE TASKS -----------------
  # --------------------------------------------------

  emulate_firebase:
    # deps: [build_functions]
    cmds:
      - firebase emulators:start

  # ---------------------------------------------------
  # ----------------- FUNCTIONS TASKS -----------------
  # ---------------------------------------------------

  install_functions:
    cmds:
      - cd functions && npm install

  build_functions_watch:
    cmds:
      - npm run build:watch --prefix functions

  build_functions:
    cmds:
      - npm run build --prefix functions
    sources:
      - functions/src/**/*
    generates:
      - functions/lib/**/*
    method: timestamp

  deploy_functions:
    deps:
      - build_functions
    cmds:
      - firebase deploy --only functions
